### ISSUE TITLE
Add a "stack" as an alternative to crossing math out

### ISSUE THREAD

**Issue by NSoiffer** [benetech/MathEditor#100]
Based on some feedback, some teachers teach students to add/subtract from both sides in a manner similar to what they learned for 2D add/subtract. E.g.,
![image](https://user-images.githubusercontent.com/1545836/36931999-59273516-1e77-11e8-91d6-70e573ad85ed.png)

One question to resolve is the alignment of the two elements of the stack.

**Comment by NSoiffer** [comment]
I can use the TeX command `\underset{lower}{original}` now that it has been fixed in mathlive. It currently centers and looks like:
![image](https://user-images.githubusercontent.com/1545836/36932033-da5368bc-1e77-11e8-825a-3072ce3fa65a.png)
`\space` can be used to add some space (which is how the example in the initial comment was generated), but it seems  wrong to require users to know/do this.

Two other things to consider:
* Should there be some indication of the first element in the stack?
* Should the second line be the same font size or shrunken as in the above example?

`Add step` needs to know about this so they go away like cross outs. Probably that should only happen if the operation is 0, although maybe we shouldn't help students by simplifying or giving a warning about adding a step when they don't cancel.

Related to the `Add step` issue is making `Calc` understand stacks.

A button (with a shortcut) need to be added.

Here's a faked up example after one step:
![image](https://user-images.githubusercontent.com/1545836/36932130-96dd0c80-1e79-11e8-9923-4cb90ebf9391.png)

**Comment by sueannma** [comment]
closing this issue and opening a new one to address the outstanding questions as issue #117
