### ISSUE TITLE
missing parentheses & brackets

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#106]
All the parenthesis and brackets disappear after hitting “add step” 

![parentheses brackets](https://user-images.githubusercontent.com/7883873/39970680-8c5b6f5a-56a4-11e8-84a8-f1e17b3e0034.jpg)

![image](https://user-images.githubusercontent.com/7883873/39970685-9fe77bc2-56a4-11e8-9f17-d06c9f9bca54.png)

**Comment by NSoiffer** [comment]
I'm having trouble replicating this. If you can still replicate this, could you copy the last line and paste it into a bug comment (it will paste as LaTeX).

Also, what is the second screenshot showing re parens going away? I don't see a problem wrt parens.

**Comment by sueannma** [comment]
The problem is that the brackets and parentheses are are apparent in the editor box, but then when I copy direclty, they are missing: 7x-13=112345
![image](https://user-images.githubusercontent.com/7883873/40027092-19231a62-578d-11e8-976d-af19e68b96af.png)

And then when i click "Add Step" they are not apparent in the history or the copied down step
![image](https://user-images.githubusercontent.com/7883873/40027141-5595614e-578d-11e8-9929-d855e05dc07f.png)

**Comment by sueannma** [comment]
3(-\frac{1}{6})(-\frac{2}{5})12345
