### ISSUE TITLE
replace with cross out results in temporary missing value

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#107]
Replace then cross out leaves an empty denominator (step 2), then the 1 returns in the denominator again (step 5)

![image](https://user-images.githubusercontent.com/7883873/39970689-be23dac2-56a4-11e8-9d59-cf01f6ec01b5.png)

**Comment by NSoiffer** [comment]
Fixed with https://github.com/benetech/MathEditor/commit/20444ff5eb28590e7e2287d31de9b3007832a1da#diff-61a482802201d78d354f41dad2cda223
