### ISSUE TITLE
symbols and operands should stay within the edit box

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#110]
in QA, when applying the fraction operand to the 7x, an additional = sign is introduced in the numerator. Also, the brackets in the denominator will extend beyond the active math text block

![image](https://user-images.githubusercontent.com/7883873/39970778-63588406-56a6-11e8-8851-0427c5e83568.png)
![image](https://user-images.githubusercontent.com/7883873/39970793-a32a8516-56a6-11e8-810f-c320ea8aeaca.png)

**Comment by NSoiffer** [comment]
Mathlive bug (same as #112 ).

**Comment by sueannma** [comment]
adding a fraction to the denominator still introduces text the bleeds beyond the text box. Below is a fake, example, but we should probably try to extend the box a tad farther, length-wise
![image](https://user-images.githubusercontent.com/7883873/40201684-a0e2f50a-59d4-11e8-9940-56d28f760765.png)

**Comment by NSoiffer** [comment]
For ease in replicating the problem, this is the expression that causes the problem:
`\frac {1}{\frac {\Bigl{(}\frac {7}{8}\Bigr{)}}{9}}`

**Comment by NSoiffer** [comment]
We have a few options:
1. Make the box taller. It will fail when we come across an even taller expression.
2. Add scroll bars when it gets tall
3. Make the box grow in height. This is probably the best solution for editing, but the overall layout might be compromised as the palettes will move.
