### ISSUE TITLE
Calculate button doesn't work when applied to certain values

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#112]
In QA, the calculate button doesn't work when applied to "-36+34" on the right or "-34+34" on the left (but does work in Staging); also introduces an error message 

![image](https://user-images.githubusercontent.com/7883873/39970882-cf0f5f02-56a7-11e8-9908-688795fda00a.png)

**Comment by NSoiffer** [comment]
The bug is in mathlive -- it is saying the selection is "-34+34 \leq". The \leq shouldn't be there. I'm looking into a fix in mathlive.
