### ISSUE TITLE
Speech to Text Broken?

### ISSUE THREAD

**Issue by BenetechSchwab** [benetech/MathEditor#16]
The Speech to Text seems to not work correctly for some reason after checkin.

**Comment by sueannma** [comment]
Jason, I just opened Galois on Chrome in incognito mode and the speech function doesn't seem to be working. Are you also able to document whether or not there is a time-out on this function? Neil also mentioned it stopped working for him only after recording and deleting a few times. 

In the case I just tried, it wasn't working on the first attempt.

**Comment by BenetechSchwab** [comment]
fixed
