### ISSUE TITLE
Update Modal Close Buttons

### ISSUE THREAD

**Issue by BenetechSchwab** [benetech/MathEditor#18]
Remove the Buttons that are called "Mark as Closed" and "Save FOr Later".

Create

Cancel - this will close the modal and NOT save any work you have done

Save - Saves your current work and closes the modal

**Comment by NSoiffer** [comment]
Any button that deletes work must be undoable or have a "are you sure?" confirmation.

**Comment by BenetechSchwab** [comment]
I agree, I added a conform dialogue  box on the cancel button
