### ISSUE TITLE
Add Loop to write out array of available problems

### ISSUE THREAD

**Issue by BenetechSchwab** [benetech/MathEditor#2]
Each example problem with have a js object.  Create an array of these objects, then iterate over them and write out the initial list of Problems on the home page.

Include the following
1.) Problem Name
2.) Original Equation
3.) Original Annotation

Also account for a blank editor instance

**Comment by sueannma** [comment]
"Problem Name" can just be incremental numbering. (e.g., 1., 2., etc.). 

This needs to be available on the home page and in the top left of the pop-up modal.

**Comment by sueannma** [comment]
Equations to provide (sorry, but I can only provide them in linear form): 
1. Find the product: 3(-1/6)(-2/5) 
2. Solve for x: 7x+13 = -1
3. Solve for x: 44/100 = x/5000
4. Solve the inequality: 3x-7 > 5
5. Sarah earns a weekly salary of $325 plus a 11.5% commission on sales at a coffee shop. How much would she make in a work week if she sold $2800 worth of merchandise?
6. What is the area of a circle with a diameter of 10 (use pi or 3.14)?
7. Angle a and angle b are supplementary. If angle a is 27 degrees, what is angle b?
8. Type your own problem
