### ISSUE TITLE
Buttons should have hover text

### ISSUE THREAD

**Issue by NSoiffer** [benetech/MathEditor#23]
Hover text and/or aria labels should be added to buttons/palettes to give more explanation about the button/palettes.

**Comment by sueannma** [comment]
I'm not sure if something is also listed in the alt-text, but what do you think about having the hover-over labels be the name of the virtual button, with the shortcut in parentheses or a colon followed by the shortcut (I'm fine with either of these options)? I think sighted users and/or users with trouble processing symbols (e.g., dyscalculia) could also benefit for lesser-known keys, such as the upper and lower bound, or symbols that might be hard to distinguish, such as plus, plus or minus, and divide. 

For example: 
- "keyboard shortcut: /" would be replaced with "fraction (/)" or "fraction: /"
- "keyboard shortcut: +-" would be replaced with "plus or minus (+-)" or "plus or minus: +-"
- "keyboard shortcut: shift+delete" would be replaced with "delete (shift+delete)" or "delete: shift+delete"

**Comment by sueannma** [comment]
symbols to consider adding (open to discussion): 
- plus (since we now have the "calculate" function)
- minus (since we now have the "calculate" function)
- pi (this is pretty common in basic geometry)

list is work in progress as I continue to look through curriculum materials.
