### ISSUE TITLE
Should use MathML for accessibility

### ISSUE THREAD

**Issue by NSoiffer** [benetech/MathEditor#26]
Using MathML will give better accessibility in most AT because they will support not just (maybe) better speech, but also navigation and braille. Potentially even sync highlighting, but that will require further work.

Note: this is a feature that needs to be implemented in mathlive.

**Comment by sueannma** [comment]
this will provide access to navigation, braille, and better speech (via MathPlayer, JAWS and ChromeVox)

**Comment by NSoiffer** [comment]
Fixed with update to mathlive.
