### ISSUE TITLE
remove black box in background that appears during editing

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#27]
problem appears behind the current equation after editing and using the cross-out function
![full black behind current equation](https://user-images.githubusercontent.com/7883873/31629252-edda2e24-b267-11e7-9141-a004450a40d7.jpg)

problem also appears in different sizes in the palette are after using the replace function 
![full black behind palette](https://user-images.githubusercontent.com/7883873/31629253-edf41f3c-b267-11e7-8ed9-972c7a84111e.jpg)
![partial black behind palette](https://user-images.githubusercontent.com/7883873/31629257-ef618602-b267-11e7-9df9-62d830847626.jpg)

**Comment by sueannma** [comment]
Now I wonder if the black box issue stems from mathlive.io. I noticed that there's a LaTex box, especially when one is still in edit mode.  

![black box on mathlive](https://user-images.githubusercontent.com/7883873/31742022-2d0e8636-b40b-11e7-8e6b-6fef991cc8e4.PNG)

**Comment by BenetechSchwab** [comment]
It doesn't appear that the mathlive.io latex box is causing this.  That is a slightly different shade of dark grey rather than black.  I am unable to replicate this on a mac browser.  Appears that this might only be happening on Windows versions of Chrome???  Is anyone experiencing this on Firefox or IE?

**Comment by sueannma** [comment]
I have not experienced this in some time, so might close for now. If we encounter it again, we can reopen this ticket
