### ISSUE TITLE
"Delete Current Step" button

### ISSUE THREAD

**Issue by BenetechSchwab** [benetech/MathEditor#3]
Move the placement of the "Delete Current Step" button so that it is an X next to the editor row.

Confirm exact functionality on this.  Functionality already exists from Neil

**Comment by sueannma** [comment]
This will delete everything related to the current step (equation and annotations).

**Comment by BenetechSchwab** [comment]
clos ethis bug out...  there is no needed case for the delete current step button

**Comment by NSoiffer** [comment]
A trash can icon was added to the "current step" that deletes what's in the current line and brings the previous line into the editor.
