### ISSUE TITLE
merge function buttons into a single "Next" button

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#31]
delete step has been moved to the current editor line; merge the remaining 3 functions ("cleanup crossouts," "copy step," and "cleanup & copy step") into a single "Next" button that is available on the current editor module

**Comment by sueannma** [comment]
Confirmed with Neil - move forward with merging the three functions into a single "Next." We will test this with users and determine if there are use cases that require these to be more explicit (and separate)

**Comment by NSoiffer** [comment]
Done, although functionality might need to change (see https://github.com/benetech/MathEditor/issues/38)
