### ISSUE TITLE
Provide default examples 

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#35]
increase to 8 examples

**Comment by sueannma** [comment]
I am only able to provide these equations in linear form, but please use the correct symbols and formatting wherever possible:

1. Find the product: 3(-1/6)(-2/5)
2. Solve for x: 7x-13 = 1
3. Solve for x: 3x+14 = 5
4. Solve the inequality: b/9-34 < -36 
5. Solve for x: Angles a and b are supplementary. Angle a is 78 degrees and angle b is equal to 3x 
6. What is the area of a circle with a diameter of 10 (use pi or the value of pi to the hundredths place)?
7. Sarah works at a coffee shop. Her weekly salary is $325 and she early 11.5% commission on sales. How much does she make if she sells $2800 in merchandise? 
8. Try your own problem

**Comment by sueannma** [comment]
Please add numbers in front of the problems. 

these need to be recreated so that they're rendered in a way that students can understand: 
1. 3(-\frac{1}{6})(-\frac{2}{5})
4. \frac{b}{9}-34<-36
5. change the degrees to the circle symbol
6. change pi to the pi symbol

**Comment by sueannma** [comment]
updated problem 4 slightly to replace the < with <=

**Comment by BenetechSchwab** [comment]
completed.
