### ISSUE TITLE
cross out with superscript button produces #?

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#37]
the replace function is not providing a blank box, but a strange #? instead, which needs to be manually replaced every time. I seem to have this issue every time I use the fraction key now. 

to replicate: 
1. pull up equation #2 
2. select the "-1" on the right side of the equation
3. select the replace function from the palette; notice the #? that appears rather than a blank box to be filled in (see screenshot)

![replace function applying odd symbols](https://user-images.githubusercontent.com/7883873/31690343-4f5ae104-b347-11e7-903c-a18663d2b194.jpg)

**Comment by NSoiffer** [comment]
I don't see a "#?" in the screenshot. Please provide step-by-step instructions on how to reproduce the problem.

**Comment by sueannma** [comment]
Yes! Thank you Neil! =)
