### ISSUE TITLE
remove duplicate copy when using next

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#38]
add logic that unless the cross-our or replace functions are used, only one additional history step should be copied (not two). See screenshot where I've typed in an original equation and then hit "Next", but two rows of history are generated instead of one. 

![dupl lines and replace symbol error](https://user-images.githubusercontent.com/7883873/31687066-0e9586c4-b33d-11e7-9bf9-f3d247e89d7b.PNG)

**Comment by NSoiffer** [comment]
Fixed with
https://github.com/benetech/MathEditor/commit/48cda38659f6c9e7f9cc57678f7b06e1c8d16042
https://github.com/benetech/MathEditor/commit/48cda38659f6c9e7f9cc57678f7b06e1c8d16042
