### ISSUE TITLE
Add a "calculate" button

### ISSUE THREAD

**Issue by NSoiffer** [benetech/MathEditor#39]
Many problems involve boring arithmetic that is not central to problem solving. We can add a _calculate_ button that works on a selection. At least as a start, because order of operation is still taught in Algebra, it should only deal with two numbers and an operator.

The button needs to recognize the various operators we have (a few versions of times and divide). It would probably also have to recognize 2d division, exponentiation, and square roots. Longer term, supporting sin, log, etc., would be needed. None of these are particularly hard, but each cases adds a few more lines of code. So for a MVP, we'd need to decide what is needed now. I suggest +, -, *, ·, ×, /, ÷, 2d division, and square root.  Juxtaposition (e.g., 3x) is not included because for _numbers_, juxtaposition is not used for multiplication.

My thought for how the button would work would be you select some simple expression to calculate, press the calculate button, and the selection is replaced by a cross out of the selection followed by the result of the calculation. E.g, here is a before and after:

![image](https://user-images.githubusercontent.com/1545836/31696011-0beda2be-b363-11e7-8a3e-5c26fc0f9724.png)

Because of potential cross outs being present (maybe from having already used the calculate button), they would need to be thrown out before attempting to do the calculation.

This button is conceptually similar to the other palette buttons, so it belongs with them.

**Comment by NSoiffer** [comment]
It turned out to me much easier to do all calculation in the selection, so that's what I implemented.

**Comment by sueannma** [comment]
Neil, the calculate button doesn't seem to be working, so I'm reopening this ticket.
