### ISSUE TITLE
annotations are not copying into the history logs

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#41]
1. Step 3 in the first screenshot - remove 7 on the left, replace 14 with 2 on the right, then added an annotation that was typed in.
2. Click Next
3. Notice how the step was simplified, producing Step 3 & 4 in the history log, but the "divide by 7" annotation remained in the "current" module. 
4. Also note that the annotation seems to be caching. The first two screenshots/edits were applied to problem 1. When I opened up problem 2, the "divide by 7" annotation was there again (see third screenshot)

![missing annotations 1](https://user-images.githubusercontent.com/7883873/31796617-4c86d8b8-b4df-11e7-8815-d736c45884c4.PNG)
![missing annotations 2](https://user-images.githubusercontent.com/7883873/31796620-501ecf76-b4df-11e7-9828-163774177bce.PNG)
![missing annotations 3](https://user-images.githubusercontent.com/7883873/31796723-c1448894-b4df-11e7-9cbf-17bec546389c.PNG)

**Comment by sueannma** [comment]
sometimes, the annotations are not showing in the "Current" module (editor), but then when one clicks next, it appears in the History logs (see screenshot)

![missing annotations 4](https://user-images.githubusercontent.com/7883873/31798250-78c9234c-b4e7-11e7-851a-f863a69b45cf.PNG)

**Comment by BenetechSchwab** [comment]
This has been fixed.
