### ISSUE TITLE
Update the available palette symbols and labels

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#43]
shorten the labels and remove the extra open parenthesis for several labels. I've tried to indicate where there are extra open parenthesis: 
- Dot Times - has ((
- Times
- Division
- Plus Minus - has ((
- Delete - has ((
- Fraction
- Superscript
- Subscript
- Square Root
- Root
- Less Than or Equal
- Greater Than or Equation
- Not Equal
- Is Equal to - //question: is there a more formal label for this sign?
- Replace
- Parentheses
- Square Brackets
- Absolute Value
- Floor
- Ceiling
- Triangle - has ((
- Angle - has ((
- Congruent - has ((
- Perpendicular - has ((
- Parallel - has ((
- Calculate

Symbols to add:
- Degree
- Pi

**Comment by BenetechSchwab** [comment]
I updated all the existing buttons.  Still need to add "Degree" and "Pi" buttons.

**Comment by NSoiffer** [comment]
I didn't make the following changes for the following reasons:
* "Delete" for the cross out is not a good choice. "Delete" means something else.
* "Superscript" is not a word most kids know. The people I worked with at ETS didn't want this word used in ClearSpeak for that reason.
* Greater Than or Equation: typo?

Answer to question about "Is Equal to": not that I know of.
