### ISSUE TITLE
Titles and original problem statement are in plain text

### ISSUE THREAD

**Issue by NSoiffer** [benetech/MathEditor#44]
The "title" on index.html and the original problem statement are just plain text. They should be math.

@sueannma : the data file should be modified to use $$'s around some latex for the math. E.g., $$7x+13=1$$. For more advanced constructs, type the expression into mathlive.io and then copy the latex from that. E.g., should the "-1/6" in the first problem really use a "/" or should it be a 2D fraction (1 over 6)? If the later, then it is `\frac{1}{6}`.

@BenetechSchwab: you probably need to call `MathLive.renderMathInDocument();` somewhere on the index.html page.

**Comment by sueannma** [comment]
agreed - see issue #35

**Comment by NSoiffer** [comment]
Fixed
