### ISSUE TITLE
calculate button not totally working

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#48]
the close parenthesis is getting removed; also hitting the "next" button generates an incorrect next step (vs. modifications in step 4, which actually looked correct before applying "Next").

![calculate not working properly](https://user-images.githubusercontent.com/7883873/31838493-ebfab20e-b591-11e7-906c-58c8254e1745.PNG)

**Comment by NSoiffer** [comment]
I can't tell what you did to see the paren go away. Can you show a before shot of using the calc button with the selection in it and an after shot showing the result of the calc button.

Same for 'next' problem.

**Comment by sueannma** [comment]
I applied calculate on 2/5+1, which produced 1.4 inline (step 5), but then I clicked “next”, you see what gets generated in step 6.

I need to catch a train and head over to testing. I will try to maneuver around this case (since simple calculations that don’t involve fractions seem to work).

We can resume investigation after testing today?

Everything else is working great!

[cid:image002.jpg@01D349A0.E3A235D0]

**Comment by sueannma** [comment]
here's another example where the calculate (on 14/7) is not working with a 2D fraction and is showing on the step where it's applied (step 6), but then copying down results in the 2 changing to a 7 (step 6), which is not correct

![calculate not working properly 2](https://user-images.githubusercontent.com/7883873/31842330-8ee5fc0c-b5a2-11e7-9dca-5bbe11e126f1.PNG)
