### ISSUE TITLE
Create fully solved problem as sample

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#50]
need an example to help get users oriented on using the tool - 
- history
- annotations (type or speak)
- next
- delete
- calculate
- editor
- palette highlight - remove, replace, more

**Comment by sueannma** [comment]
This should be presented as the first example on the page. Ideally, would have Jason's updated UI before creating this example, but I'm working on it.

**Comment by BenetechSchwab** [comment]
I can easily add this once we have the actual problem and steps created.  Waiting on either Sue-Ann or Neil to create this.

**Comment by sueannma** [comment]
we are implementing via "Getting Started" (issue #73 )
