### ISSUE TITLE
replace default math problems 

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#57]
https://matheditor-qa.diagramcenter.org/development01/development01.html

- 10/26 students have only learned about fraction multiplication & division, so replace default problems.

**Comment by sueannma** [comment]
Using this tool
1. Find the product: 3(-\frac{1}{6})(-\frac{2}{5})=
2. Find the product: -\frac{2}{5}(-\frac{1}{2})(-\frac{5}{6})=
3. Find the quotient: \frac{55}{\frac{1}{2}}=
4. Find the quotient: \frac{3}{10}\div (\frac{5}{8})= 
5. Solve for x: 7x-13=1
6. Solve the inequality: \frac{b}{9}-34\leq -36
7.
8. Try your own problem

**Comment by sueannma** [comment]
"Using this Tool" is the first out of the 9 default problems, and should appear in the top left. Starting numbering of actual problems at 1.

**Comment by BenetechSchwab** [comment]
updated in development with these equations

**Comment by NSoiffer** [comment]
Removed trailing '='s and fixed wording to "earns".
