### ISSUE TITLE
add a sample math problem

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#58]
Provide the example in the top left space of the 3-by-3 problem matrix (on the main page). This will be presented in a pop-up image modal, similar to the editor.

- The title for this "problem" should be: "
![using this tool_image](https://user-images.githubusercontent.com/7883873/32014873-35e6d0ec-b974-11e7-973c-6ab9bb13854a.PNG)
Using this Tool"

**Comment by BenetechSchwab** [comment]
done
