### ISSUE TITLE
cross out button not working with certain symbols

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#62]
Neil mentioned this was linked to Mathlive.io, but still wanted to document the issue. 

to replicate:
1.  select the is equal to (= sign with ? on top) from the palette
2. try to cross out the is equal to sign
3. notice how the bottom = gets crossed out, but the ? remains; the entire expression (including the ?) should be crossed out

**Comment by NSoiffer** [comment]
Fixed with update to mathlive.
