### ISSUE TITLE
editor periodically freezes and user cannot continue editing the current equation

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#63]
I'm not sure how to replicate, but on several instances, the modal would freeze and prevent further editing (typing via keyboard or palette) or selection of the math equation (current). If one were to save and then reopen the same problem, the user was then able to edit again. 

again, I'm not sure why this was happening, but it occurred several times during 10/26 testing with students.

**Comment by BenetechSchwab** [comment]
has this happened recently?

**Comment by sueannma** [comment]
this hasn't happened in a while, so closing
