### ISSUE TITLE
Can't type a dollar sign

### ISSUE THREAD

**Issue by NSoiffer** [benetech/MathEditor#65]
mathlive isn't accepting a '$' as input. Useful to have when doing problems involving dollars. Same for cents (¢). Both can be entered using their unicode:
* ¢ --  \char"0000A2
* $ -- \char"000024

Obviously, that's not very friendly, but as a fallback, could be used in a palette button.

**Comment by sueannma** [comment]
actually, one can't really type spaces or words into the math equation editor either (annotations are fine)

**Comment by NSoiffer** [comment]
'$' now seems to work, but it eats the character in front of it. E.g., in a blank area, type '-$', the '-' goes away.

**Comment by sueannma** [comment]
consider adding a \textrm button later to accommodate text in equations

**Comment by NSoiffer** [comment]
Fixed
