### ISSUE TITLE
Math Editor UI is misaligned

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#67]
problems: 
- symbols are wrapping onto 4 lines
- old UI colors displaying (no blue)
- undo button showing up prematurely
- audio icon below annotations
- box for annotations extending too far down
- equation editor (math) font is too small again
- modal window not adapting to screen size (extends below the page)

![editor misaligned](https://user-images.githubusercontent.com/7883873/32177264-17271ad2-bd47-11e7-8f92-54646262dc07.PNG)

**Comment by NSoiffer** [comment]
Committed missing styles file
