### ISSUE TITLE
Improve look of introjs help

### ISSUE THREAD

**Issue by NSoiffer** [benetech/MathEditor#69]
Introjs is currently being used for help. The colors and transparency are not good.

I've played around some and added to styles.css comments about relevant introjs styles that can be modified. I think it is better than before, but someone with better color sense should definitely fix it up.

Also, it would be good to have the 'done' button where the 'next' button is. I think this involves hacking the minjs JS code.

**Comment by BenetechSchwab** [comment]
i changed the coloring of all styles to something a little better.

**Comment by sueannma** [comment]
please make sure the selection is around the entire area the descriptions pertain to
- for 1: box should be wider and taller
- for 2: box should include the microphone

**Comment by BenetechSchwab** [comment]
all in progress and most are completed.

**Comment by BenetechSchwab** [comment]
completed.
