### ISSUE TITLE
Add sample problem to demonstrate available features

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#73]
the below example should be on the main page, in, the menu bar, to the left of the "Contact Us" link. Clicking on "Getting Started" will bring up the sample problem below, with the "Help" (tour) to introduce new users to the features and workflow available through the Benetech Math Editor. 

![sample problem](https://user-images.githubusercontent.com/7883873/33396015-20da3e3e-d4fc-11e7-8b64-9f5d17fd2bab.PNG)

**Comment by sueannma** [comment]
step 2: 
7x\enclose{updiagonalstrike downdiagonalstrike}[2px solid red]{-13}=\enclose{updiagonalstrike downdiagonalstrike}[2px solid red]{1+13}14

step 4: 
\enclose{updiagonalstrike downdiagonalstrike}[2px solid red]{\frac{7x}{7}}^x=\enclose{updiagonalstrike downdiagonalstrike}[2px solid red]{\frac{14}{7}}^2

**Comment by BenetechSchwab** [comment]
in progress

**Comment by BenetechSchwab** [comment]
Completed!
