### ISSUE TITLE
shift "calc", "cross out" and "replace" to the far left

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#74]
"cross out" and "replace" buttons should be next to the "calc" button since there are all functions rather than symbols or operations. It's fine to include a bit of a gap between the symbols/operations vs. the cross out / replace / calc keys.

**Comment by BenetechSchwab** [comment]
completed

**Comment by sueannma** [comment]
also need to move calc to the left.

**Comment by BenetechSchwab** [comment]
completed.
