### ISSUE TITLE
read math equations out loud

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#76]
Add a native feature that allows math equations to be read aloud to a student who is not using an AT device (similar to Bookshare Web Reader, such a feature could be very beneficial for students with dyscalculia)

**Comment by NSoiffer** [comment]
## Key bindings to speak content
Here are the key bindings that are currently part of MathLive (and hence, Galois). We can (and probably should) change these at some point.

The bigger issue is that IMHO, some notions such as parent and sibling are probably not intuitive. That's harder to change.

### Windows
    Ctrl-Alt-Up           'speakParent'
    Ctrl-Alt-Down         'speakGroup'
    Ctrl-Alt-Left         'speakLeftSibling'
    Ctrl-Alt-Right        'speakRightSibling'
    Ctrl-Alt-Shift-Down   'speakSelection'

### Mac
    Ctrl-Meta-Up            'speakParent'
    Ctrl-Meta-Down          'speakGroup'
    Ctrl-Meta-Left          'speakLeftSibling'
    Ctrl-Meta-Right         'speakRightSibling'
    Ctrl-Meta-Shift-Down    'speakSelection'
