### ISSUE TITLE
\triangle producing a different symbol

### ISSUE THREAD

**Issue by NSoiffer** [benetech/MathEditor#91]
Type `\triangle` followed by enter and you get ≜ (`\triangleq`).

This is a [mathlive bug](https://github.com/arnog/mathlive/issues/44) caused by using the larger text sequence

**Comment by NSoiffer** [comment]
If you use up/down arrow, you can select from a list of options, on which is `triangle`. Not that easily discoverable, so other options need to be considered.

**Comment by arnog** [comment]
A solution for this would be to define an inline shortcut using `config.inlineShortcuts:{'triangle': '\\triangle'}` so that just typing `triangle` (and not `\triangle`) would result in the triangle symbol appearing.
