### ISSUE TITLE
Additional Math Problem Sets

### ISSUE THREAD

**Issue by sueannma** [benetech/MathEditor#97]
Problem Set 2:

1. Find the product: 3(-\frac{1}{6})(-\frac{2}{5})
2. Solve for x: 7x-12=2
3. Solve for x: 3x+14=5
4. Solve the inequality: \frac{b}{9}-34\leq -36
5. Solve for x: Angles a and b are supplementary. Angle a is 78 \degree and angle b is equal to 3x
6. What is the area of a circle with a diameter of 10 (use \pi or the value of \pi to the hundredths place)?
7. Sarah works at a coffee shop. Her weekly salary is $325 and she early 11.5% commission on sales. How much does she make if she sells $2800 in merchandise?
8. Try your own problem

Problem Set 3: 
1. Find the product: 4(-\frac{2}{9})(-\frac{9}{4})
2. Find the product: (-\frac{3}{8})(-\frac{2}{7})(-\frac{4}{6})
2. Find the product: (-\frac{4}{3})(\frac{2}{8})(-\frac{6}{2})
3. Solve for x: 5x-10=10
4. Solve for x: 6x+14=8
5. Solve for y: -7y\leq 14
6. Solve for y: -3x+13>9
7. Solve the inequality: \frac{b}{8}-33\leq -35
9. Try your own problem

**Comment by BenetechSchwab** [comment]
Completed except for two small issues.

Problem Set #2, Problem 5:  History & Title is showing "$$\degree$$"
Problem Set #2, Problem 5:  History & Title is showing "$$\pi$$"

**Comment by sueannma** [comment]
closing and creating new bug ticket to address incorrect symbol rendering
